FROM python

# Installs additional packages
RUN pip install lightgbm flask scikit-learn

# Downloads training data
# RUN curl https://example-url/path-to-data/data-filename --output /root/data-filename
ENV AIP_STORAGE_URI=gs://aakash-test-env/dataset/scikit_model/
ENV AIP_HEALTH_ROUTE=/ping
ENV AIP_PREDICT_ROUTE=/predict
ENV AIP_HTTP_PORT=8080
# Copies the trainer code to the docker image.
# COPY your-path-to/model.py /root/model.py
COPY . ./
# gsutil cp -r gs://aakash-test-env/dataset/scikit_model/model.pkl ./

# RUN chmod +x entrypoint.sh

# Sets up the entry point to invoke the trainer.
ENTRYPOINT ["python", "serving_model.py"]